Repository SHDS-ESC/ForestOfOmok, pull requests merged in 2025-05, with the labels that each got.

#1 issue_pr_template 추가
  .github/ISSUE_TEMPLATE/기능-요청.md
  .github/ISSUE_TEMPLATE/기타-이슈.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서

#26 #2 상대경로 절대경로 수정 및 css 수정
  forestOfOmok/src/main/java/dao/UserDAO.java
  forestOfOmok/src/main/java/model/User.java
  forestOfOmok/src/main/webapp/css/enter.css
  forestOfOmok/src/main/webapp/css/login.css
  forestOfOmok/src/main/webapp/css/signUp.css
  forestOfOmok/src/main/webapp/css/style.css
  forestOfOmok/src/main/webapp/html/enter.html
  forestOfOmok/src/main/webapp/html/findId.html
  forestOfOmok/src/main/webapp/html/findPwd.html
  forestOfOmok/src/main/webapp/html/join.html
  forestOfOmok/src/main/webapp/html/login.html
  forestOfOmok/src/main/webapp/html/start.html
  forestOfOmok/src/main/webapp/js/signUp.js
Labels: 디자인

#32 회원가입, 로그인 기능추가
  forestOfOmok/src/main/java/controller/JoinServlet.java
  forestOfOmok/src/main/java/controller/LoginServlet.java
  forestOfOmok/src/main/java/dao/UserDAO.java
  forestOfOmok/src/main/webapp/css/login.css
  forestOfOmok/src/main/webapp/css/signUp.css
  forestOfOmok/src/main/webapp/css/style.css
  forestOfOmok/src/main/webapp/html/findId.html
  forestOfOmok/src/main/webapp/html/join.html
  forestOfOmok/src/main/webapp/html/login.html
Labels: 기능추가

#29 ajax + 서버 연동 성공 및 프로필 조회
  forestOfOmok/src/main/java/controller/MainServlet.java
  forestOfOmok/src/main/java/dao/UserDAO2.java
  forestOfOmok/src/main/java/dao/UserDAO2Impl.java
  forestOfOmok/src/main/java/model/Profile.java
  forestOfOmok/src/main/webapp/css/style.css
  forestOfOmok/src/main/webapp/html/main.html
  forestOfOmok/src/main/webapp/html/modal.html
Labels: 기능추가

#35 방 만들기, 방 리스트 조회 등 메인작업
  forestOfOmok/src/main/java/controller/MainServlet.java
  forestOfOmok/src/main/java/dao/UserDAO.java
  forestOfOmok/src/main/java/dao/UserDAO2.java
  forestOfOmok/src/main/java/dao/UserDAO2Impl.java
  forestOfOmok/src/main/java/model/Game.java
  forestOfOmok/src/main/webapp/css/style.css
  forestOfOmok/src/main/webapp/html/main.html
  forestOfOmok/src/main/webapp/html/modal.html
Labels: 기능추가

#37 지원, 가희, 선우 코드 병합 최종입니다.
  forestOfOmok/src/main/java/controller/FindIdServlet.java
  forestOfOmok/src/main/java/controller/JoinServlet.java
  forestOfOmok/src/main/java/controller/LoginServlet.java
  forestOfOmok/src/main/java/controller/MainServlet.java
  forestOfOmok/src/main/java/controller/StartServlet.java
  forestOfOmok/src/main/java/dao/UserDAO.java
  forestOfOmok/src/main/java/dao/UserDAO2.java
  forestOfOmok/src/main/java/dao/UserDAO2Impl.java
  forestOfOmok/src/main/java/model/Game.java
  forestOfOmok/src/main/java/model/History.java
  forestOfOmok/src/main/java/model/Rank.java
  forestOfOmok/src/main/webapp/css/signUp.css
  forestOfOmok/src/main/webapp/css/style.css
  forestOfOmok/src/main/webapp/html/enter.html
  forestOfOmok/src/main/webapp/html/findId.html
  forestOfOmok/src/main/webapp/html/join.html
  forestOfOmok/src/main/webapp/html/login.html
  forestOfOmok/src/main/webapp/html/main.html
  forestOfOmok/src/main/webapp/html/modal.html
  forestOfOmok/src/main/webapp/html/start.html
  forestOfOmok/src/main/webapp/img/findBtn.png
  forestOfOmok/src/main/webapp/img/findBtnBold.png
  forestOfOmok/src/main/webapp/js/signUp.js
Labels: 기능추가
